=== AKisseleff/projet/src/main/resources/STB.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://univ.fr/stb" xmlns:tns="http://univ.fr/stb">

	<xs:simpleType name="Prio">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="1" />
			<xs:maxInclusive value="10" />
		</xs:restriction>
	</xs:simpleType>

	<xs:element name="Personne">
		<xs:complexType>
			<xs:all>
				<xs:element name="Nom" type="xs:string" />
				<xs:element name="gender" type="xs:boolean" />
				<xs:element name="Prenom" type="xs:string" />
			</xs:all>
		</xs:complexType>
	</xs:element>

	<xs:element name="ExigenceFonctionnelle">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Identifiant" type="xs:string" />
				<xs:element name="Description" type="xs:string" />
				<xs:element name="Priorite" type="xs:positiveInteger" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="STB">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Id" type="xs:positiveInteger" />
				<xs:element name="Titre" type="xs:string" />
				<xs:element name="Version" type="xs:string" />
				<xs:element name="Date" type="xs:date" />
				<xs:element name="Description" type="xs:string" />

				<xs:element name="Client">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Entite" type="xs:string" />
							<xs:element name="Contact" type="xs:string" />
							<xs:element name="CodePostal" type="xs:positiveInteger" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>

				<xs:element name="Equipe">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="tns:Personne" minOccurs="2"
								maxOccurs="7" />
						</xs:sequence>

					</xs:complexType>
				</xs:element>

				<xs:element name="Fonctionnalite" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Description" type="xs:string" />
							<xs:element ref="tns:ExigenceFonctionnelle" maxOccurs="unbounded"
								minOccurs="2" />
						</xs:sequence>
						<xs:attribute name="Priorite" type="tns:Prio" />
					</xs:complexType>
				</xs:element>

				<xs:element name="Commentaire" type="xs:string"
					minOccurs="0" />

			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="ListSTB">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="tns:STB" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== AKisseleff/projet/src/main/resources/STB.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:ListSTB xmlns:tns="http://univ.fr/stb"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://univ.fr/stb STB.xsd ">
	<tns:STB>
		<Id>1</Id>
		<Titre>Tir au panier</Titre>
		<Version>1.5</Version>
		<Date>2007-02-10</Date>
		<Description>Jeux de basker pour IOS et android</Description>
		<Client>
			<Entite>EA</Entite>
			<Contact>Max Brooks</Contact>
			<CodePostal>46230</CodePostal>
		</Client>
		<Equipe>
			<tns:Personne>
				<Nom>Jean</Nom>
				<gender>true</gender>
				<Prenom>Patrick</Prenom>
			</tns:Personne>
			<tns:Personne>
				<Nom>Dupont</Nom>
				<gender>false</gender>
				<Prenom>Annick</Prenom>
			</tns:Personne>
			<tns:Personne>
				<Nom>Grenier</Nom>
				<gender>true</gender>
				<Prenom>Maxime</Prenom>
			</tns:Personne>
		</Equipe>
		<Fonctionnalite Priorite="1">
			<Description>Pouvoir jouer en ligne</Description>
			<tns:ExigenceFonctionnelle>
				<Identifiant>A001</Identifiant>
				<Description>Le lag ne doit pas dépasser 2s </Description>
				<Priorite>8</Priorite>
			</tns:ExigenceFonctionnelle>
			<tns:ExigenceFonctionnelle>
				<Identifiant>A002</Identifiant>
				<Description>Le temps de recherche d'une partie ne doit pas dépasser une minute</Description>
				<Priorite>7</Priorite>
			</tns:ExigenceFonctionnelle>
		</Fonctionnalite>
		<Fonctionnalite Priorite="5">
			<Description>Le joueur peut personnaliser son jeu</Description>
			<tns:ExigenceFonctionnelle>
				<Identifiant>C250</Identifiant>
				<Description>L'utilisateur peut définir le physique de tous ses joueurs </Description>
				<Priorite>8</Priorite>
			</tns:ExigenceFonctionnelle>
			<tns:ExigenceFonctionnelle>
				<Identifiant>C681</Identifiant>
				<Description>L'utilisateur peut choisir les couleurs de maillots</Description>
				<Priorite>6</Priorite>
			</tns:ExigenceFonctionnelle>
		</Fonctionnalite>
		<Commentaire>Il est aussi possible de jouer localement contre une IA.</Commentaire>
	</tns:STB>
	<tns:STB>
		<Id>2</Id>
		<Titre>Rugby Pari</Titre>
		<Version>6.5</Version>
		<Date>2006-05-26</Date>
		<Description>Site de pari sportif pour le rugby</Description>
		<Client>
			<Entite>ABCD Corp.</Entite>
			<Contact>Jean Bak</Contact>
			<CodePostal>89230</CodePostal>
		</Client>
		<Equipe>
			<tns:Personne>
				<Nom>Marc</Nom>
				<gender>true</gender>
				<Prenom>Marcel</Prenom>
			</tns:Personne>
			<tns:Personne>
				<Nom>Albert</Nom>
				<gender>false</gender>
				<Prenom>Louise</Prenom>
			</tns:Personne>
		</Equipe>
		<Fonctionnalite Priorite="1">
			<Description>L'utilisateur doit pouvoir, pendant le match, parier sur le prochain joueur a marquer un essai </Description>
			<tns:ExigenceFonctionnelle>
				<Identifiant>AUJ4</Identifiant>
				<Description>Les changements de joeur doivent être actualisé dans l'application en moins de 30s.</Description>
				<Priorite>9</Priorite>
			</tns:ExigenceFonctionnelle>
			<tns:ExigenceFonctionnelle>
				<Identifiant>AUJ7</Identifiant>
				<Description>L'application doit prendre en compte les cartons.</Description>
				<Priorite>2</Priorite>
			</tns:ExigenceFonctionnelle>
		</Fonctionnalite>
	</tns:STB>
</tns:ListSTB>
